import { Prisma } from '@prisma/client';
import { Router } from 'express';
import { z } from 'zod';
import { prisma } from '../../config/prisma.js';
import { asyncHandler } from '../../lib/async-handler.js';
import { authenticate } from '../../middleware/authenticate.js';
import { requirePermission } from '../../middleware/authorize.js';

const rangeSchema = z.object({ from: z.coerce.date().optional(), to: z.coerce.date().optional() });
const activeSale: Prisma.SaleWhereInput = { status: { in: ['COMPLETED', 'PARTIALLY_RETURNED', 'RETURNED'] } };

export const reportsRoutes = Router(); reportsRoutes.use(authenticate);
reportsRoutes.get('/dashboard', requirePermission('dashboard:read'), asyncHandler(async (_req, res) => {
  const start = new Date(); start.setHours(0, 0, 0, 0); const end = new Date(start); end.setDate(end.getDate() + 1);
  const [sales, returns, expenses, lowStock, customers, recentSales, topItems, purchases, products, outOfStock, suppliers, customerLedger, supplierLedger, paymentBreakdown, profitItems] = await Promise.all([
    prisma.sale.aggregate({ where: { ...activeSale, createdAt: { gte: start, lt: end } }, _sum: { grandTotal: true, amountPaid: true }, _count: true }),
    prisma.saleReturn.aggregate({ where: { createdAt: { gte: start, lt: end }, status: 'COMPLETED' }, _sum: { refundAmount: true }, _count: true }),
    prisma.expense.aggregate({ where: { expenseDate: { gte: start, lt: end }, status: 'RECORDED' }, _sum: { amount: true }, _count: true }),
    prisma.productVariant.count({ where: { status: 'ACTIVE', stockQuantity: { lte: prisma.productVariant.fields.minStockLevel } } }),
    prisma.customer.count({ where: { isActive: true } }),
    prisma.sale.findMany({ take: 8, orderBy: { createdAt: 'desc' }, include: { customer: { select: { name: true } } } }),
    prisma.saleItem.groupBy({ by: ['productNameSnapshot'], where: { sale: { createdAt: { gte: start, lt: end }, ...activeSale } }, _sum: { quantity: true, finalAmount: true }, orderBy: { _sum: { quantity: 'desc' } }, take: 5 }),
    prisma.purchase.aggregate({ where: { purchaseDate: { gte: start, lt: end }, status: { not: 'CANCELLED' } }, _sum: { grandTotal: true }, _count: true }),
    prisma.product.count({ where: { status: 'ACTIVE' } }),
    prisma.productVariant.count({ where: { status: 'ACTIVE', stockQuantity: 0 } }),
    prisma.supplier.count({ where: { isActive: true } }),
    prisma.customerLedgerEntry.aggregate({ _sum: { amount: true } }),
    prisma.supplierLedgerEntry.aggregate({ _sum: { amount: true } }),
    prisma.payment.groupBy({ by: ['method'], where: { kind: 'RECEIPT', createdAt: { gte: start, lt: end } }, _sum: { amount: true } }),
    prisma.saleItem.findMany({ where: { sale: { createdAt: { gte: start, lt: end }, ...activeSale } }, select: { quantity: true, returnedQuantity: true, purchaseCostSnapshot: true, taxableAmount: true } }),
  ]);
  const grossProfit = profitItems.reduce((sum, item) => { const units = item.quantity - item.returnedQuantity; return sum + Number(item.taxableAmount) * units / item.quantity - Number(item.purchaseCostSnapshot) * units; }, 0);
  res.json({ success: true, data: { period: { from: start, to: end }, sales: { count: sales._count, gross: sales._sum?.grandTotal ?? 0, collected: sales._sum?.amountPaid ?? 0 }, returns: { count: returns._count, amount: returns._sum.refundAmount ?? 0 }, expenses: { count: expenses._count, amount: expenses._sum.amount ?? 0 }, purchases: { count: purchases._count, amount: purchases._sum.grandTotal ?? 0 }, profit: grossProfit - Number(expenses._sum.amount ?? 0), lowStock, outOfStock, products, customers, suppliers, customerOutstanding: customerLedger._sum.amount ?? 0, supplierOutstanding: supplierLedger._sum.amount ?? 0, paymentBreakdown, recentSales, topItems } });
}));
reportsRoutes.use(requirePermission('reports:read'));
reportsRoutes.get('/sales', asyncHandler(async (req, res) => { const range = rangeSchema.parse(req.query); const where: Prisma.SaleWhereInput = { ...activeSale, createdAt: range.from || range.to ? { gte: range.from, lte: range.to } : undefined }; const [summary, byMethod, rows] = await Promise.all([prisma.sale.aggregate({ where, _sum: { subtotal: true, itemDiscount: true, billDiscount: true, cgst: true, sgst: true, igst: true, grandTotal: true, amountPaid: true, balanceDue: true }, _count: true }), prisma.payment.groupBy({ by: ['method'], where: { sale: where, kind: 'RECEIPT' }, _sum: { amount: true }, _count: true }), prisma.sale.findMany({ where, take: 1000, orderBy: { createdAt: 'desc' }, include: { customer: { select: { name: true } } } })]); res.json({ success: true, data: { summary, byMethod, rows } }); }));
reportsRoutes.get('/gst', asyncHandler(async (req, res) => { const range = rangeSchema.parse(req.query); const rows = await prisma.saleItem.groupBy({ by: ['taxRateSnapshot'], where: { sale: { ...activeSale, createdAt: range.from || range.to ? { gte: range.from, lte: range.to } : undefined } }, _sum: { taxableAmount: true, cgst: true, sgst: true, igst: true, finalAmount: true } }); res.json({ success: true, data: rows }); }));
reportsRoutes.get('/profit', asyncHandler(async (req, res) => { const range = rangeSchema.parse(req.query); const items = await prisma.saleItem.findMany({ where: { sale: { ...activeSale, createdAt: range.from || range.to ? { gte: range.from, lte: range.to } : undefined } }, select: { quantity: true, returnedQuantity: true, purchaseCostSnapshot: true, taxableAmount: true, discountAmount: true } }); const summary = items.reduce((value, item) => { const sold = item.quantity - item.returnedQuantity; const ratio = sold / item.quantity; value.revenue += Number(item.taxableAmount) * ratio; value.cost += Number(item.purchaseCostSnapshot) * sold; value.discount += Number(item.discountAmount) * ratio; return value; }, { revenue: 0, cost: 0, discount: 0 }); res.json({ success: true, data: { ...summary, grossProfit: summary.revenue - summary.cost, marginPercent: summary.revenue ? (summary.revenue - summary.cost) / summary.revenue * 100 : 0 } }); }));
reportsRoutes.get('/stock', asyncHandler(async (_req, res) => { const rows = await prisma.productVariant.findMany({ where: { status: 'ACTIVE' }, include: { product: { include: { category: true, brand: true } } }, orderBy: { stockQuantity: 'asc' } }); const totals = rows.reduce((result, item) => ({ units: result.units + item.stockQuantity, costValue: result.costValue + item.stockQuantity * Number(item.purchaseCost), retailValue: result.retailValue + item.stockQuantity * Number(item.retailPrice) }), { units: 0, costValue: 0, retailValue: 0 }); res.json({ success: true, data: { totals, rows } }); }));
reportsRoutes.get('/expenses', asyncHandler(async (req, res) => { const range = rangeSchema.parse(req.query); const where: Prisma.ExpenseWhereInput = { status: 'RECORDED', expenseDate: range.from || range.to ? { gte: range.from, lte: range.to } : undefined }; const [summary, byCategory, rows] = await Promise.all([prisma.expense.aggregate({ where, _sum: { amount: true }, _count: true }), prisma.expense.groupBy({ by: ['categoryId'], where, _sum: { amount: true }, _count: true }), prisma.expense.findMany({ where, include: { category: true }, orderBy: { expenseDate: 'desc' } })]); res.json({ success: true, data: { summary, byCategory, rows } }); }));
reportsRoutes.get('/customers', asyncHandler(async (_req, res) => { const rows = await prisma.customer.findMany({ include: { ledgerEntries: { select: { amount: true } }, _count: { select: { sales: true } } }, orderBy: { name: 'asc' } }); const data = rows.map(({ ledgerEntries, ...item }) => ({ ...item, outstanding: ledgerEntries.reduce((sum, entry) => sum + Number(entry.amount), 0) })); res.json({ success: true, data: { summary: { customers: data.length, outstanding: data.reduce((sum, item) => sum + item.outstanding, 0), repeatCustomers: data.filter((item) => item._count.sales > 1).length }, rows: data } }); }));
reportsRoutes.get('/suppliers', asyncHandler(async (_req, res) => { const rows = await prisma.supplier.findMany({ include: { ledgerEntries: { select: { amount: true } }, _count: { select: { purchases: true } } }, orderBy: { name: 'asc' } }); const data = rows.map(({ ledgerEntries, ...item }) => ({ ...item, outstanding: ledgerEntries.reduce((sum, entry) => sum + Number(entry.amount), 0) })); res.json({ success: true, data: { summary: { suppliers: data.length, outstanding: data.reduce((sum, item) => sum + item.outstanding, 0), activeSuppliers: data.filter((item) => item.isActive).length }, rows: data } }); }));
reportsRoutes.get('/returns', asyncHandler(async (req, res) => { const range = rangeSchema.parse(req.query); const createdAt = range.from || range.to ? { gte: range.from, lte: range.to } : undefined; const [sales, purchases] = await Promise.all([prisma.saleReturn.aggregate({ where: { createdAt, status: 'COMPLETED' }, _sum: { refundAmount: true }, _count: true }), prisma.purchaseReturn.aggregate({ where: { createdAt, status: 'COMPLETED' }, _sum: { totalAmount: true }, _count: true })]); res.json({ success: true, data: { summary: { saleReturns: sales._count, customerRefunds: sales._sum.refundAmount ?? 0, purchaseReturns: purchases._count, supplierReturns: purchases._sum.totalAmount ?? 0 } } }); }));
reportsRoutes.get('/product-profit', asyncHandler(async (req, res) => { const range = rangeSchema.parse(req.query); const items = await prisma.saleItem.findMany({ where: { sale: { ...activeSale, createdAt: range.from || range.to ? { gte: range.from, lte: range.to } : undefined } }, select: { productNameSnapshot: true, skuSnapshot: true, quantity: true, returnedQuantity: true, purchaseCostSnapshot: true, taxableAmount: true } }); const grouped = new Map<string, { product: string; sku: string; units: number; revenue: number; cost: number }>(); for (const item of items) { const units = item.quantity - item.returnedQuantity; const current = grouped.get(item.skuSnapshot) ?? { product: item.productNameSnapshot, sku: item.skuSnapshot, units: 0, revenue: 0, cost: 0 }; current.units += units; current.revenue += Number(item.taxableAmount) * units / item.quantity; current.cost += Number(item.purchaseCostSnapshot) * units; grouped.set(item.skuSnapshot, current); } const rows = [...grouped.values()].map((item) => ({ ...item, profit: item.revenue - item.cost })).sort((a, b) => b.profit - a.profit); res.json({ success: true, data: { summary: { products: rows.length, profit: rows.reduce((sum, item) => sum + item.profit, 0) }, rows } }); }));
