import { Router } from 'express';
import { z } from 'zod';
import { prisma } from '../../config/prisma.js';
import { ApiError } from '../../lib/api-error.js';
import { asyncHandler } from '../../lib/async-handler.js';
import { authenticate } from '../../middleware/authenticate.js';
import { requirePermission } from '../../middleware/authorize.js';

const taxSchema = z.object({ name: z.string().trim().min(2).max(80), rate: z.coerce.number().finite().min(0).max(100), isActive: z.boolean().optional() });
const couponBaseSchema = z.object({ code: z.string().trim().min(2).max(50).transform((value) => value.toUpperCase()), description: z.string().trim().max(240).optional(), discountType: z.enum(['PERCENTAGE', 'FIXED']), discountValue: z.coerce.number().finite().positive(), minimumAmount: z.coerce.number().finite().min(0).default(0), maximumDiscount: z.coerce.number().finite().positive().nullable().optional(), startsAt: z.coerce.date().nullable().optional(), endsAt: z.coerce.date().nullable().optional(), isActive: z.boolean().default(true) });
const couponSchema = couponBaseSchema.refine((item) => item.discountType !== 'PERCENTAGE' || item.discountValue <= 100, { message: 'Percentage discount cannot exceed 100%.', path: ['discountValue'] }).refine((item) => !item.startsAt || !item.endsAt || item.endsAt > item.startsAt, { message: 'End date must be after start date.', path: ['endsAt'] });
const settingsSchema = z.object({ storeProfile: z.object({ name: z.string().trim().min(2).max(120), address: z.string().trim().max(500).optional(), city: z.string().trim().max(100), state: z.string().trim().max(100), gstin: z.string().trim().max(20).optional(), phone: z.string().trim().max(20).optional(), currency: z.literal('INR').default('INR'), timezone: z.string().trim().min(2).max(80).default('Asia/Kolkata') }), invoiceConfiguration: z.object({ prefix: z.string().trim().min(1).max(20), returnPrefix: z.string().trim().min(1).max(20), purchasePrefix: z.string().trim().min(1).max(20), purchaseReturnPrefix: z.string().trim().min(1).max(20), footer: z.string().trim().max(500).optional(), returnPolicy: z.string().trim().max(1000).optional() }) });
const id = z.string().uuid();

export const settingsRoutes = Router(); settingsRoutes.use(authenticate);
settingsRoutes.get('/invoice-profile', asyncHandler(async (_req, res) => { const rows = await prisma.setting.findMany({ where: { key: { in: ['store.profile', 'invoice.configuration'] } } }); res.json({ success: true, data: Object.fromEntries(rows.map((row) => [row.key, row.value])) }); }));
settingsRoutes.get('/tax-rates', asyncHandler(async (_req, res) => res.json({ success: true, data: await prisma.taxRate.findMany({ orderBy: { rate: 'asc' } }) })));
settingsRoutes.post('/tax-rates', requirePermission('taxes:manage'), asyncHandler(async (req, res) => { const item = await prisma.taxRate.create({ data: taxSchema.parse(req.body) }); res.status(201).json({ success: true, data: item }); }));
settingsRoutes.patch('/tax-rates/:id', requirePermission('taxes:manage'), asyncHandler(async (req, res) => { const item = await prisma.taxRate.update({ where: { id: id.parse(req.params.id) }, data: taxSchema.partial().parse(req.body) }); res.json({ success: true, data: item }); }));
settingsRoutes.get('/coupons', requirePermission('coupons:manage'), asyncHandler(async (_req, res) => res.json({ success: true, data: await prisma.coupon.findMany({ orderBy: { createdAt: 'desc' } }) })));
settingsRoutes.post('/coupons/validate', asyncHandler(async (req, res) => { const input = z.object({ code: z.string(), amount: z.coerce.number().nonnegative() }).parse(req.body); const now = new Date(); const coupon = await prisma.coupon.findFirst({ where: { code: input.code.trim().toUpperCase(), isActive: true, OR: [{ startsAt: null }, { startsAt: { lte: now } }], AND: [{ OR: [{ endsAt: null }, { endsAt: { gte: now } }] }] } }); if (!coupon || Number(coupon.minimumAmount) > input.amount) throw new ApiError(400, 'INVALID_COUPON', 'Coupon is invalid or minimum purchase amount is not met.'); const raw = coupon.discountType === 'PERCENTAGE' ? input.amount * Number(coupon.discountValue) / 100 : Number(coupon.discountValue); const discount = Math.min(raw, coupon.maximumDiscount ? Number(coupon.maximumDiscount) : raw, input.amount); res.json({ success: true, data: { coupon, discount: discount.toFixed(2) } }); }));
settingsRoutes.post('/coupons', requirePermission('coupons:manage'), asyncHandler(async (req, res) => { const item = await prisma.coupon.create({ data: couponSchema.parse(req.body) }); res.status(201).json({ success: true, data: item }); }));
settingsRoutes.patch('/coupons/:id', requirePermission('coupons:manage'), asyncHandler(async (req, res) => { const item = await prisma.coupon.update({ where: { id: id.parse(req.params.id) }, data: couponBaseSchema.partial().parse(req.body) }); res.json({ success: true, data: item }); }));
settingsRoutes.get('/', requirePermission('settings:manage'), asyncHandler(async (_req, res) => { const rows = await prisma.setting.findMany({ where: { key: { in: ['store.profile', 'invoice.configuration'] } } }); res.json({ success: true, data: Object.fromEntries(rows.map((row) => [row.key, row.value])) }); }));
settingsRoutes.put('/', requirePermission('settings:manage'), asyncHandler(async (req, res) => { const input = settingsSchema.parse(req.body); await prisma.$transaction([prisma.setting.upsert({ where: { key: 'store.profile' }, update: { value: input.storeProfile }, create: { key: 'store.profile', value: input.storeProfile } }), prisma.setting.upsert({ where: { key: 'invoice.configuration' }, update: { value: input.invoiceConfiguration }, create: { key: 'invoice.configuration', value: input.invoiceConfiguration } }), prisma.auditLog.create({ data: { actorId: req.auth!.id, action: 'SETTINGS_UPDATED', entityType: 'setting', entityId: 'store', ipAddress: req.ip } })]); res.json({ success: true, data: input }); }));

export const auditRoutes = Router(); auditRoutes.use(authenticate, requirePermission('audit:read'));
auditRoutes.get('/', asyncHandler(async (req, res) => { const take = z.coerce.number().int().min(1).max(500).default(100).parse(req.query.take); const logs = await prisma.auditLog.findMany({ take, orderBy: { createdAt: 'desc' }, include: { actor: { select: { id: true, name: true, email: true } } } }); res.json({ success: true, data: logs }); }));
