import { PaymentMethod, Prisma } from '@prisma/client';
import { prisma } from '../../config/prisma.js'; import { D } from '../../lib/money.js'; import type { SupplierInput } from './suppliers.schema.js';
async function code(tx: Prisma.TransactionClient) { const key = 'SUPPLIER'; await tx.invoiceSequence.upsert({ where: { key }, update: {}, create: { key, prefix: 'SUP', year: 0, nextNumber: 1 } }); const row = await tx.invoiceSequence.update({ where: { key }, data: { nextNumber: { increment: 1 } } }); return `SUP-${String(row.nextNumber - 1).padStart(6, '0')}`; }
export const suppliersRepository = {
  async list(search?: string) { const where: Prisma.SupplierWhereInput = search ? { OR: [{ name: { contains: search, mode: 'insensitive' } }, { company: { contains: search, mode: 'insensitive' } }, { mobile: { contains: search } }] } : {}; const items = await prisma.supplier.findMany({ where, orderBy: { name: 'asc' }, include: { ledgerEntries: { select: { amount: true } }, _count: { select: { purchases: true } } } }); return items.map(({ ledgerEntries, ...item }) => ({ ...item, outstanding: ledgerEntries.reduce((sum, entry) => sum.plus(entry.amount), D(0)) })); },
  get: (id: string) => prisma.supplier.findUnique({ where: { id }, include: { purchases: { orderBy: { purchaseDate: 'desc' }, take: 20 }, ledgerEntries: { orderBy: { createdAt: 'desc' }, take: 100 }, payments: { orderBy: { createdAt: 'desc' }, take: 50 } } }),
  create(input: SupplierInput, actorId: string, ip?: string) { return prisma.$transaction(async (tx) => { const { openingBalance, ...data } = input; const item = await tx.supplier.create({ data: { ...data, supplierCode: await code(tx) } }); if (D(openingBalance).gt(0)) await tx.supplierLedgerEntry.create({ data: { supplierId: item.id, type: 'OPENING_BALANCE', amount: openingBalance, referenceType: 'supplier', referenceId: item.id } }); await tx.auditLog.create({ data: { actorId, action: 'SUPPLIER_CREATED', entityType: 'supplier', entityId: item.id, ipAddress: ip } }); return item; }); },
  update(id: string, data: Prisma.SupplierUpdateInput, actorId: string, ip?: string) { return prisma.$transaction(async (tx) => { if (!await tx.supplier.findUnique({ where: { id } })) return null; const item = await tx.supplier.update({ where: { id }, data }); await tx.auditLog.create({ data: { actorId, action: 'SUPPLIER_UPDATED', entityType: 'supplier', entityId: id, ipAddress: ip } }); return item; }); },
  pay(id: string, input: { amount: string; method: string; cashSessionId?: string | null; reference?: string; notes?: string }, actorId: string, ip?: string) { return prisma.$transaction(async (tx) => { if (!await tx.supplier.findFirst({ where: { id, isActive: true } })) return null; if (input.method === 'CASH' && !await tx.cashSession.findFirst({ where: { id: input.cashSessionId ?? '', status: { in: ['OPEN', 'REOPENED'] } } })) return { invalidCash: true as const }; const payment = await tx.payment.create({ data: { supplierId: id, cashSessionId: input.method === 'CASH' ? input.cashSessionId : null, kind: 'SUPPLIER_PAYMENT', method: input.method as PaymentMethod, amount: input.amount, reference: input.reference, notes: input.notes } }); await tx.supplierLedgerEntry.create({ data: { supplierId: id, type: 'PAYMENT', amount: D(input.amount).negated(), referenceType: 'payment', referenceId: payment.id } }); await tx.auditLog.create({ data: { actorId, action: 'SUPPLIER_PAYMENT', entityType: 'payment', entityId: payment.id, ipAddress: ip } }); return { invalidCash: false as const, payment }; }); },
};
