import { useQuery } from '@tanstack/react-query';
import { AlertTriangle, Banknote, ReceiptText, RotateCcw, ShoppingBag, UsersRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../services/api';
import { dateTimeFormatter, formatINR } from '../utils/format';

interface Dashboard { sales: { count: number; gross: string; collected: string }; returns: { count: number; amount: string }; expenses: { count: number; amount: string }; purchases: { count: number; amount: string }; profit: number; lowStock: number; outOfStock: number; products: number; customers: number; suppliers: number; customerOutstanding: string; supplierOutstanding: string; recentSales: Array<{ id: string; invoiceNumber: string; createdAt: string; grandTotal: string; status: string; customer: { name: string } | null }>; topItems: Array<{ productNameSnapshot: string; _sum: { quantity: number; finalAmount: string } }> }
export function DashboardPage() {
  const dashboard = useQuery({ queryKey: ['dashboard'], queryFn: () => api<Dashboard>('/reports/dashboard'), refetchInterval: 60_000 }); const data = dashboard.data?.data;
  const cards = [{ label: "Today's sales", value: formatINR(data?.sales.gross ?? 0), note: `${data?.sales.count ?? 0} bills`, icon: Banknote }, { label: "Today's purchases", value: formatINR(data?.purchases.amount ?? 0), note: `${data?.purchases.count ?? 0} receipts`, icon: ShoppingBag }, { label: "Today's profit", value: formatINR(data?.profit ?? 0), note: 'after today’s expenses', icon: Banknote }, { label: 'Expenses', value: formatINR(data?.expenses.amount ?? 0), note: `${data?.expenses.count ?? 0} entries`, icon: ReceiptText }, { label: 'Returns', value: formatINR(data?.returns.amount ?? 0), note: `${data?.returns.count ?? 0} returns`, icon: RotateCcw }, { label: 'Low / out of stock', value: `${data?.lowStock ?? 0} / ${data?.outOfStock ?? 0}`, note: 'variants need attention', icon: AlertTriangle }, { label: 'Customer outstanding', value: formatINR(data?.customerOutstanding ?? 0), note: `${data?.customers ?? 0} customers`, icon: UsersRound }, { label: 'Supplier outstanding', value: formatINR(data?.supplierOutstanding ?? 0), note: `${data?.suppliers ?? 0} suppliers`, icon: UsersRound }];
  return <div className="mx-auto max-w-7xl"><section className="overflow-hidden rounded-3xl bg-ink p-7 text-white sm:p-9"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-gold-400">Live operations</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Today at The Trends Mart</h2><p className="mt-3 text-stone-400">Sales, cash, stock and account activity update automatically.</p></div><Link className="inline-flex rounded-xl bg-gold-400 px-5 py-3 text-sm font-bold text-ink" to="/pos"><ShoppingBag className="mr-2 h-5 w-5" />Generate bill</Link></div></section><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map((card) => <article className="card p-5" key={card.label}><div className="flex justify-between"><p className="text-sm font-semibold text-stone-500">{card.label}</p><card.icon className="h-5 w-5 text-gold-600" /></div><p className="mt-4 text-2xl font-black">{card.value}</p><p className="mt-1 text-xs text-stone-500">{card.note}</p></article>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-[1.5fr_1fr]"><section className="card overflow-hidden"><div className="flex items-center justify-between border-b p-5"><h3 className="font-bold">Recent sales</h3><Link to="/sales" className="text-sm font-semibold text-gold-600">View all</Link></div><div className="divide-y">{data?.recentSales.map((sale) => <Link to={`/sales/${sale.id}/invoice`} key={sale.id} className="flex items-center justify-between p-4 hover:bg-stone-50"><div><p className="font-semibold">{sale.invoiceNumber}</p><p className="text-xs text-stone-500">{sale.customer?.name ?? 'Walk-in'} · {dateTimeFormatter.format(new Date(sale.createdAt))}</p></div><p className="font-bold">{formatINR(sale.grandTotal)}</p></Link>)}{!data?.recentSales.length && <p className="p-10 text-center text-sm text-stone-500">No sales yet today.</p>}</div></section><section className="card p-5"><div className="flex justify-between"><h3 className="font-bold">Top items today</h3><UsersRound className="h-5 w-5 text-gold-600" /></div><div className="mt-4 space-y-4">{data?.topItems.map((item, index) => <div key={item.productNameSnapshot} className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-stone-100 text-xs font-bold">{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.productNameSnapshot}</p><p className="text-xs text-stone-500">{item._sum.quantity} units</p></div><span className="text-sm font-bold">{formatINR(item._sum.finalAmount)}</span></div>)}{!data?.topItems.length && <p className="py-8 text-center text-sm text-stone-500">Product rankings appear after sales.</p>}</div></section></div></div>;
}
